name: Pull Request Manager

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPMRC_AUTH_TOKEN: ${{ secrets.NPMRC_AUTH_TOKEN }}
      CI: true
    strategy:
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn lint:ci
      - run: yarn build
      - run: yarn test:ci
